### ISSUE TITLE
Pull Assigner notifies all team members

### ISSUE THREAD

**Issue by eborden** [pullreminders/backlog#131]
### What is happening

Pull Assigner notifies all team members when a review has been assigned.

### What should happen

Only the team member that has review assigned from Pull Assigner should get notified.

### Why

The amount of noise that team notifications produce makes Pull Assigner not worth the hassle. We want our signal to noise ratio to be low so engineers need only pay attention to the reviews that they are eventually assigned by Pull Assigner.

**Comment by abinoda** [comment]
@eborden Thanks for submitting this. Are you referring to Pull Reminders Slack notifications or email notifications?

**Comment by eborden** [comment]
Any notification :smile:

**Comment by abinoda** [comment]
@eborden Ok, can you share your workflow? Are you manually assigning reviews to the team for Pull Assigner or automating it with CODEOWNER?

**Comment by eborden** [comment]
So far I've used manual assignment to the team as a test of the functionality.

**Comment by abinoda** [comment]
@eborden Got it. There's no way for us to stop GitHub's email notifications but we can definitely prevent Pull Reminders from sending notifications about the team review request, which I'm guessing is the far bigger pain point given the directness and noisiness of Slack notifications? Would this work?

**Comment by eborden** [comment]
@abinoda that may work, but it also provides a poor experience for team members who have not opted in to slack reminders and instead use email reminders. So we'd likely not utilize this tool.

**Comment by abinoda** [comment]
@eborden Makes sense. The problem you're describing is definitely legitimate.

The best solution I can think of would be to allow you to specify team members in Pull Assigner instead of on GitHub.  So you'd create a team on GitHub with no members, then specify who the members are within Pull Assigner. This way you could assign a review to a GitHub team without GitHub notifying a bunch of people. If we implemented this do you think your team would use Pull Assigner?

I'd love to hear thoughts from other Pull Assigner users @jisung @marksb @brad-decker @nullren.

**Comment by eborden** [comment]
That sounds like a reasonable workaround.

**Comment by abinoda** [comment]
@eborden Another option would be for everyone to simply set up a gmail filter that mutes the team review request notifications. Would this work? I know it's a little inconvenient but it seems like it's less work overall than my previous suggestion.

We'd address the Slack notification issue on our end.

**Comment by abinoda** [comment]
Also pinging @benmanns and @geoffharcourt for input on this if they have ideas!

**Comment by eborden** [comment]
@abinoda it is possible that could work as well. It just seems like there is a flaw in the design if outside applications need to be configured in tandem to make this usable for teams.

**Comment by benmanns** [comment]
Dropping Slack notifications would be better than the status quo for us (everyone is already getting emailed with standard CODEOWNERS setup).

Internally we're somewhat particular about GitHub team setup, but could make this work. The way I'd probably do it is to create a `pull_reminder_app_<team>` team with no assignees and leave our `<team>` team set up, which would allow manual pings within other parts of GitHub.

**Comment by abinoda** [comment]
@eborden I agree that a Gmail filter isn't ideal but I think it might be the best solution for now.

I'm also considering the fact that the GitHub notifications for team review requests aren't always something folks will want to avoid. In certain cases I can see teams wanting everyone on the team to be made aware of new pull requests even though specific people will be assigned to actually review it.

For now we'll move forward with disabling team review request Slack notifications when the team is hooked up to Pull Assigner (cc: @benmanns), and for email suggest Gmail filtering:

<img width="725" alt="screen shot 2019-02-20 at 10 32 38 am" src="https://user-images.githubusercontent.com/50083/53111757-f184ee80-34fa-11e9-9f0f-8405ad8ae2b5.png">

<img width="726" alt="screen shot 2019-02-20 at 10 33 51 am" src="https://user-images.githubusercontent.com/50083/53111796-0ceff980-34fb-11e9-94ef-812b724d44cc.png">

We're working on launching improved documentation for Pull Assigner so will be sure to add this.

**Comment by nullren** [comment]
I quite like the idea of have a separate "pull reminders team" alias sort of thing. one issue that I've come across is that I actually can't assign a PR to my team anymore 😅 .

**Comment by abinoda** [comment]
@nullren 

> One issue that I've come across is that I actually can't assign a PR to my team anymore.

How come?

**Comment by nullren** [comment]
well, every time a PR is sent to my team, pull assigner removes it if there's a person on the team already. granted, everyone still gets the emails (this issue), but the team is no longer there so I think members lose a little bit of empowerment to participate.

**Comment by abinoda** [comment]
@nullren That behavior is actually a setting. See the "Team review request" option in your [Pull Assigner settings](https://pullreminders.com/installs/1229663/assigner/teams/12/edit) and set it to "Do not delete".

Also, in cases where you assign the team but a reviewer is assigned already, do you want Pull Assigner to not assign additional reviewers like it does currently, or do you still want it to assign another reviewer (in addition to the person already assigned).

**Comment by eborden** [comment]
> In certain cases I can see teams wanting everyone on the team to be made aware of new pull requests even though specific people will be assigned to actually review it.

This seems like a setting that Pull Assigner would expose. If I want everyone on my team to be notified then I probably want Pull Reminders to also be notifying, not just email.

**Comment by abinoda** [comment]
> This seems like a setting that Pull Assigner would expose. If I want everyone on my team to be notified then I probably want Pull Reminders to also be notifying, not just email.

@eborden Yeah, I agree with that. Just making the case that those team review request emails are not *always* a bad thing.

**Comment by abinoda** [comment]
@nullren Let me know if that setting addresses the issue you were having!

**Comment by nullren** [comment]
> @nullren Let me know if that setting addresses the issue you were having!

@abinoda ohhh, sorry. yea, that should be fine.

> Also, in cases where you assign the team but a reviewer is assigned already, do you want Pull Assigner to not assign additional reviewers like it does currently, or do you still want it to assign another reviewer (in addition to the person already assigned).

I think not assigning like it does currently is great.

**Comment by abinoda** [comment]
We deployed a change so Pull Reminders no longer sends DM notifications for team review requests *if the team has Pull Assigner enabled* (see pseudo-code logic below). This solves the issue of user's getting spammed with DM notifications, but I do have the concern that there could be cases where users could want want DM notifications for the team hooked up to Pull Assigner?

In follow-up to this:

* @benmanns Let me know if this change benefits your team!
* @nullren I'm curious what your thoughts are on this change, if any 🤷‍♂️ 
* @eborden With this change and the Gmail filters discussed earlier, is your team able to move forward and continue using the tool?

Please also note that the email notification "solution" is now documented here:
https://docs.pullpanda.com/products/assigner/disabling-team-emails

### New logic for DM notifications

```ruby
if team.pull_assigner_enabled?
  team.auto_assign_reviewers
else
  team.send_slack_dm_for_review_request
end
```

**Comment by abinoda** [comment]
@eborden I'm marking this issue as closed per my previous comment. Please let me know if you continue to have any problems around this.

**Comment by marksb** [comment]
@abinoda - thanks for being open to feedback. 

Not sure I have much to add to this thread. The above change is helpful for us.

A few team members do use email notifications and it does create a lot of noise for them. I think each person has their own system to handle those notifications though.

**Comment by nullren** [comment]
> A few team members do use email notifications and it does create a lot of noise for them. I think each person has their own system to handle those notifications though.

my teammates are now complaining about that, too. i really like @benmanns idea:

> The way I'd probably do it is to create a `pull_reminder_app_<team>` team with no assignees and leave our `<team>` team set up, which would allow manual pings within other parts of GitHub.

since that also ties into what github does already with notifications. it seems kind of janky, but it seems the most usable.

**Comment by abinoda** [comment]
@nullren Ok, sounds like no ones biting on my Gmail filter solution? 😝 

I gave this some more thought, and I think there's a reasonable "in-between" solution. The idea would be to let you specify an "alias" team for your actual GitHub Team. So for example, if your team is `Backend`, you could specify another GitHub Team called `Backend-PullAssigner` as an alias. Then, you could request a review from `Backend-PullAssigner` to get the same behavior as requesting the `Backend` team, the only difference being that no one gets email notifications.

What do you all think of this idea?

cc: @eborden @benmanns

**Comment by brad-decker** [comment]
@abinoda i love that idea, this just came up for our team who is getting swamped with notifications in various apps they use to manage their github notificaitons .

**Comment by nullren** [comment]
@abinoda that seems like it would cut a lot of the noise for my teammates

**Comment by abinoda** [comment]
Ok, I think I'm sold on the idea. Will get this into development today and try to get it out ASAP

**Comment by brad-decker** [comment]
@abinoda any idea how this will work with code owners if a review is required from code owners?

**Comment by abinoda** [comment]
@brad-decker You'd have to provide a little more context, but there's no reason why the "proxy team" (I'm going with label instead of "alias team") can't be added to CODEOWNERs instead of whatever is there now.

**Comment by Walther** [comment]
Another potential approach idea: see how things are done in Rust land with the rust-highfive bot user and the `r` commands. E.g. here: `https://github.com/rust-lang/rust/pull/58761`

**Comment by abinoda** [comment]
@Walther Thanks for sharing that! That's awesome. I think we could add a command like that down the road as another option. The one thing that a command would lack is the ability to tie it into CODEOWNERS, which isn't a problem with a proxy team.

**Comment by brad-decker** [comment]
@abinoda if the proxy team is empty then the issue is that requiring reviews from codeowners is not a viable option in github settings

**Comment by abinoda** [comment]
@brad-decker Ah, I see your problem now. Hmmm, that's a tough one. In the context of your overall workflow I'm wondering if having that setting enabled is absolutely necessary for compliance versus just using the `Required approving reviews`?

As an absolute worst case scenario, you could keep your settings the way they are and address the email notification issue with email filters like I was suggesting earlier.

Open to other suggestions.

**Comment by brad-decker** [comment]
You're correct, I think this is a requirement that could easily be disabled. As long as people from the team are being assigned. I'm good with this approach as written 👍 (proxy teams)

**Comment by abinoda** [comment]
🎉 Proxy teams is live – let me know how it works!

**Comment by eborden** [comment]
Experimenting with this now. Thanks for jumping on this so quickly!

**Comment by eborden** [comment]
I noticed that team reviewer deletion is currently broken with proxies. On the positive end this doesn't have any negative effects for notification, since the proxy has no members, unless your settings require all reviewers to sign off for merge.

**Comment by abinoda** [comment]
> I noticed that team reviewer deletion is currently broken with proxies.

Thanks for reporting this! Will get this fixed shortly.

**Comment by abinoda** [comment]
@eborden Proxy team review request deletion is fixed

**Comment by eborden** [comment]
@abinoda The solution is working great. I'm going to close this issue as a success!

**Comment by nullren** [comment]
@abinoda we've set up the proxy team for a while now, but as a result, PRs assigned to the original (non-proxy) team still get routed through pull-assigner. imo, that shouldn't be the case — PRs assigned to the original team should be left alone.

**Comment by abinoda** [comment]
@nullren That makes sense. Pretty simple change on our end, should be able to push a fix for this shortly.

**Comment by abinoda** [comment]
@nullren This change is deployed. Can you post back when you've confirmed that its behaving the way you wanted?
