### ISSUE TITLE
As a PR Author, I would like to receive a DM when a build/check fails on my PR

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#69]

**Comment by abinoda** [comment]
From @ashanbrown:

> When CI results come in, positive or negative, there are actions I can take immediately. For CI successes, I want to know the status of a PR review, so I can know to merge my PR. For CI failures, I want to know what failed immediately so I can make changes and push up a fix.
>
> Fwiw, while we use CircleCI, we don't use CircleCI Checks. We also use Code Climate, which is another result that could be immediately actionable.

**Comment by abinoda** [comment]
@ashanbrown I wanted to follow-up on this. You had mentioned before that you don't use [CircleCI Checks](https://circleci.com/blog/see-the-status-of-your-circleci-workflows-in-github/). Is this still the case? If so, would you mind explaining why? I've started planning out development for this, but I don't think it makes sense to build this around something *other* than the Checks API.

**Comment by abinoda** [comment]
@rouge8 @zan-rosenthal @taylor-cedar @xeger @ccpost would you mind sharing what CI tool(s) you use so I can look into what's required to support them?

**Comment by rouge8** [comment]
We’re using Travis.

**Comment by ccpost** [comment]
We're using CircleCI, though at the moment our Circle config file doesn't use Workflows, which seems to be necessary to report status through the GitHub Checks API (https://circleci.com/docs/2.0/enable-checks/). We plan to re-configure soon, though.

**Comment by xeger** [comment]
We're using Circle workflows, plus a dash of TeamCity.

**Comment by majormoses** [comment]
I have orgs using travis-ci.org, travis-ci.com, circle-ci, jenkins, and [atlantis](https://www.runatlantis.io).

**Comment by abinoda** [comment]
@xeger @taylor-cedar @zan-rosenthal @ashanbrown @ccpost @majormoses @rouge8 This is released in closed beta and I've enabled it for your accounts. You can enable it from "Your DM Settings". Note that you'll need to install an additional GitHub App to enable the webhooks needed for this. Also, this feature does NOT use GitHub's [new checks API](https://developer.github.com/v3/checks/). Instead it uses [commit statuses](https://developer.github.com/v3/repos/statuses/) since all CI tools seem to already hook into that.

Please let me know your feedback! Things I'm looking for feedback on:
- Is the overall functionality and format of the Slack message good?
- For now I have the substrings `circleci`, `travis-ci`, and `codeship` whitelisted so that any failed check containing one of those substrings in its name will trigger a Slack DM. Let me know if you'd prefer to be able to control which checks are whitelisted via substring match or regex.

**Comment by taylor-cedar** [comment]
@abinoda That is great! A couple people on our team mentioned they wanted this. We currently use Jenkins though. It would be amazing if we could just type in any status check name. We possibly are going to switch CIs, so ideally it would be better if I could ask for any string (full match. I don't think regex is necessary)

**Comment by abinoda** [comment]
@taylor-cedar Happy to add a field for setting specific check names. Just for reference could you post a screenshot of your checks so I can see the displayed names?

**Comment by taylor-cedar** [comment]
Sure. Here is a screenshot. As you can see Jenkins builds are completely unique to your build name (and don't say jenkins), so it makes sense to allow custom names.

<img width="841" alt="screen shot 2018-12-24 at 12 53 55 am" src="https://user-images.githubusercontent.com/25646493/50391774-94490880-0716-11e9-928e-d0662a2ae50b.png">

**Comment by abinoda** [comment]
@taylor-cedar Awesome. Will add a field for this shortly.

**Comment by abinoda** [comment]
@taylor-cedar Ok, just added a text field for typing in substring matches for check names. Please let me know how it works!

<img width="695" alt="screen shot 2018-12-27 at 11 48 02 am" src="https://user-images.githubusercontent.com/50083/50489456-5cb7b600-09cd-11e9-9b3d-0ea27e40b2ae.png">

cc: @xeger @majormoses @rouge8 @ccpost @zan-rosenthal

**Comment by taylor-cedar** [comment]
@abinoda I am not seeing it work on our repo. Both our status checks end in `tests`, but I am not getting alerted for some reason in Slack.

**Comment by majormoses** [comment]
I got some DM's 
![image](https://user-images.githubusercontent.com/3145127/50822644-0f99e500-12e7-11e9-9b36-d2250c4e1f11.png)

With the following config under `My DM settings` for the project
![image](https://user-images.githubusercontent.com/3145127/50822695-30623a80-12e7-11e9-810b-e242bc5f6026.png)

**Comment by majormoses** [comment]
I am gonna see if modifying it to one of `travis-ci/(push|pr)` would do what I expect and only send one DM which would be nice.

**Comment by abinoda** [comment]
I'm looking into sending one DM after all checks instead of sending separate DMs for each individual check. Not sure I can do this easily with GitHub's API but we'll see.

**Comment by majormoses** [comment]
I validated that you can use `travis-ci/push` to only get one notification and that it will not match the pr one.

**Comment by abinoda** [comment]
@taylor-cedar @elifiner Looping you guys back into this thread since you seem to be encountering a similar issue with not receiving failed CI notifications.

I can't reproduce the issue but I have a theory that it's because right now Pull Reminders uses the `sender` property in the [webhook payload](https://developer.github.com/v3/activity/events/types/#statusevent) to determine the user to notify. But I'm wondering if maybe for some reason the `sender` property is getting set to something other than you. I'm deploying a change now to use the `commit[author]` property to determine who to DM instead, and I'd like to see if that results in you guys properly getting notified.

**Comment by abinoda** [comment]
@taylor-cedar @elifiner Ok, the change is deployed. Let me know if you're able to get notifications now.

**Comment by finereli** [comment]
I like your theory, I think the sender is set to whoever set up CI in the first place and not the person with the PR. I'll test this tomorrow!

**Comment by taylor-cedar** [comment]
Thanks @abinoda and sorry for the delayed response. I will test this tomorrow morning and let you know.

**Comment by taylor-cedar** [comment]
@abinoda It's working now! Thanks for building this. It works perfectly.

**Comment by abinoda** [comment]
@taylor-cedar Great!

**Comment by finereli** [comment]
Working for me as well, great work Abi!

**Comment by ashanbrown** [comment]
@abinoda I finally got around to enabling this.  Thanks for putting me on the beta.  I'm seeing DMs for builds that I haven't triggered myself.  I'm not sure if that's intended or not.  Some are triggered by people outside my organization (by PRs on public projects), which is definitely just noise to me.  I'd really like to see this only for PRs that I've authored.

Also, you asked about why I didn't use checks in circleci.  I didn't find the information they show on their github checks page very useful so I shut it off on circleci just about as soon as I had enabled it.  I found that I'd rather scan/click the CI status on the PR.

**Comment by abinoda** [comment]
@ashanbrown 

>  I'm seeing DMs for builds that I haven't triggered myself. I'm not sure if that's intended or not. Some are triggered by people outside my organization (by PRs on public projects), which is definitely just noise to me.

Yikes – has that happened recently, like in the past few hours? Just pushed a change this afternoon that changed some of the logic so I want to double check.

> Also, you asked about why I didn't use checks in circleci. I didn't find the information they show on their github checks page very useful so I shut it off on circleci just about as soon as I had enabled it. I found that I'd rather scan/click the CI status on the PR.

Yep makes sense. For now Pull Reminders isn't even listening to Checks API because no one appears to be using it yet.

**Comment by abinoda** [comment]
@ashanbrown 

>  I'd really like to see this only for PRs that I've authored.

I can definitely update the logic to enforce this.

**Comment by ashanbrown** [comment]
> Yikes – has that happened recently, like in the past few hours? Just pushed a change this afternoon that changed some of the logic so I want to double check.

I haven't had the setting enabled long enough to say. Happened at 4:25 PM PT today fwiw.

**Comment by abinoda** [comment]
@ashanbrown Ok, the logic right now is notifying the COMMIT author whenever a build fails for one of their commits.  I'm guessing what could have happened is that a build failed for an old commit of yours that is in someone else branch and somehow had a build failure?

Can you quickly trace one of the notifications you got that was weird to see if it fits what I just described? Then I'll go ahead and implement a fix.

**Comment by abinoda** [comment]
@ashanbrown I just deployed an update so that you are only notified if you are the author of the PR on the branch where the build error occurred. Can you let me know if things work better now?

@majormoses @taylor-cedar @elifiner Please let me know if you notice any adverse changes to your CI notifications!

**Comment by kaiden-dragon** [comment]
@abinoda hey man, so I've tried to use this feature as follows:
![image](https://user-images.githubusercontent.com/43593050/50942897-331a8680-14c5-11e9-9e47-a4daa8d68dc2.png)
![image](https://user-images.githubusercontent.com/43593050/50942901-37df3a80-14c5-11e9-9cf1-90cea6b78698.png)
But it doesn't work? Maybe I've been inputting the wrong names?

**Comment by abinoda** [comment]
@kaiden-dragon While I was working on the last change I noticed something else that could've caused this to not work for some users,  which I fixed. Can you try some new failed builds now and see if it works now?

**Comment by abinoda** [comment]
For more info, the issue I fixed was previously this was relying on the commit author ID, which GitHub only sets in certain cases where it can match email addresses.

**Comment by kaiden-dragon** [comment]
@abinoda 
![image](https://user-images.githubusercontent.com/43593050/50944828-01a5b900-14cd-11e9-98f6-68d6b05fdcf3.png)
Hi, it still doesn't work? any clue on what could be wrong lol

**Comment by abinoda** [comment]
@kaiden-dragon lets take this off thread, will email you again

**Comment by abinoda** [comment]
@kaiden-dragon Your issue has been resolved.

For anyone else reading this – the issue was that @kaiden-dragon's checks were using GitHub's [new Checks API](https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/), which I hadn't added support for since not a lot of people seemed to be using it. Pull Reminders now *does* support the new Checks API as well as traditional commit status hooks.

**Comment by NejcZupec** [comment]
@abinoda Is this feature enabled for all deploys?

I'm facing the same issue as @kaiden-dragon described. We also use Github's checks API and I don't get a notification, when a build fails.

Settings:
<img width="330" alt="screenshot 2019-01-30 at 10 20 01" src="https://user-images.githubusercontent.com/1460732/51971070-a1c18300-2478-11e9-8dda-745a75015d30.png">

Failing PR checks:
<img width="692" alt="screenshot 2019-01-30 at 10 20 47" src="https://user-images.githubusercontent.com/1460732/51971128-bd2c8e00-2478-11e9-85e8-0c0533121c45.png">







BTW: I also don't get notified, when a merge conflict happens.

**Comment by abinoda** [comment]
@NejcZupec Yeah, @kaiden-dragon's issue was resolved and the update is applied to all accounts. One thing I'd suggest is to make sure that the [Pull Reminders CI Notifications App](https://github.com/apps/pull-reminders-ci-notifications/installations/new) has been enabled for all repos on your org. You won't get notifications for repos where that app has not been enabled. Could you double check that?

Could you open a separate issue for problems with merge conflict notifications? That's a whole different beast.

**Comment by NejcZupec** [comment]
@abinoda I checked the app. The repo where we're running PullReminders has permissions:

<img width="797" alt="screenshot 2019-01-30 at 20 27 37" src="https://user-images.githubusercontent.com/1460732/52006981-bd0aad80-24cd-11e9-969a-6b1a932bb54a.png">

Do I have to enable the app for all repos within the organization?

**Comment by abinoda** [comment]
@NejcZupec Based on that setting, you'll only get CI notifications for PRs on that repo. If you want to get CI notifications for PRs on other repos, you need to enable those repos. In general, I'd recommend enabling that app for all repos within the organization.

**Comment by NejcZupec** [comment]
@abinoda Ok, I enabled the app for all repos. Will see, if this helps. Thank you!

**Comment by NejcZupec** [comment]
@abinoda Yesterday I enabled the app for all repos and I started receiving notifications about merge conflicts:

<img width="499" alt="screenshot 2019-01-31 at 13 27 32" src="https://user-images.githubusercontent.com/1460732/52054290-4ff22900-255c-11e9-9810-c67219a3d347.png">

Not sure why this action helped, because the app had been enabled for that particular repo already before.

However, I still do not receive notifications about CircleCI failures.

**Comment by abinoda** [comment]
@NejcZupec Can you email me at abi@pullreminders.com? Let's investigate further offthread.

**Comment by darmalovan** [comment]
I'm still trying to get alerts on Travis, I've enabled it the notification GH app for the specific repo, still not seeing any alert on slack - anything I need to take into account? Tried also to put `Travis CI, Travis CI - Pull Request` but nothing seemed to work.

**Comment by amree** [comment]
Is there a way for us to get DM when the build passed?

**Comment by jordanjennings** [comment]
We're trying to figure out how to use DMs to be notified of Jenkins PR build failures. We've enabled both Pull Panda and Pull Reminders (CI Notifications) but no matter what DM filter we use there's no notification sent. I've tried lots of combinations of things with no luck.

Here is an example of the failed check:
<img width="600" src="https://user-images.githubusercontent.com/1031913/66927369-abd2e400-effd-11e9-8f45-2df1dda81979.png">

Here's the pull reminder DM config:
<img width="300" src="https://user-images.githubusercontent.com/1031913/66927389-b8efd300-effd-11e9-8193-cfedd5924b41.png">

What am I missing?

Also - is there an option to be notified on any check failure? Does it accept a regex or a wildcard, etc?

**Comment by sergiofbsilva** [comment]
> Is there a way for us to get DM when the build passed?

@abinoda This would be great 🎉 💪

**Comment by adrian-skybaker** [comment]
>Does it accept a regex or a wildcard, etc?

Have been hunting around for docs, it looks like this PR is the closest there is. Looks like others are confused as well, https://github.community/t/how-to-set-strings-for-failed-ci-checks-of-scheduled-reminders/122637 . 

I think you need some sort of hint/help text explaining what actually goes in this field, and what it's matching on.

Also it would be good if there was an obvious way to just say "all" failed CI checks.

**Comment by adrian-skybaker** [comment]
....also, it's odd having real-time alerts (which are really useful) hidden away in "Scheduled Reminders".

**Comment by Drarok** [comment]
> ....also, it's odd having real-time alerts (which are really useful) hidden away in "Scheduled Reminders".

Agreed! I ended up reading this thread because I had to Google where to find the settings as the checks aren't working for me. Looked in the repo settings, organisation settings, the "Settings" link in Slack for the GitHub bot before giving up, frustrated.
